// Twelve-season color analysis system.
// Two layers per season:
//   • swatches  — the 6 hero colors shown in the editorial strip. A curated,
//                 wearable SUBSET of `reference` (display ⊂ reference), so what a
//                 man sees is calmer/menswear-tuned but never off-system.
//   • reference — ~12 menswear-weighted anchors used ONLY by the ΔE classifier
//                 to tag products. Never shown. Denser = more accurate matching.
//                 Anchors stay characteristic to each season; cross-season overlap
//                 is handled at match time (a product can match several seasons).

const SEASONS = [
  {
    key: "bright-spring",
    family: "Spring",
    name: "Bright Spring",
    note: "Warm, clear, saturated — the brightest of the warm palettes.",
    swatches: [
      { hex: "#E85D3D", label: "Poppy" },
      { hex: "#F2A900", label: "Marigold" },
      { hex: "#4FB477", label: "Clear Green" },
      { hex: "#2FB6AD", label: "Bright Teal" },
      { hex: "#2D6FE0", label: "True Blue" },
      { hex: "#F4EFD8", label: "Ivory" },
    ],
    reference: [
      { hex: "#F4EFD8", label: "Ivory" },
      { hex: "#D8CFB6", label: "Warm Stone" },
      { hex: "#C49A5E", label: "Camel" },
      { hex: "#E85D3D", label: "Poppy" },
      { hex: "#D6402F", label: "Clear Red" },
      { hex: "#F2A900", label: "Marigold" },
      { hex: "#F4C534", label: "Golden Yellow" },
      { hex: "#4FB477", label: "Clear Green" },
      { hex: "#2FB6AD", label: "Bright Teal" },
      { hex: "#2D6FE0", label: "True Blue" },
      { hex: "#1F4FB0", label: "Cobalt" },
      { hex: "#20324F", label: "Warm Navy" },
    ],
  },
  {
    key: "true-spring",
    family: "Spring",
    name: "True Spring",
    note: "Warm and clear, a touch softer than Bright — golden-based.",
    swatches: [
      { hex: "#EFE3C8", label: "Warm Cream" },
      { hex: "#C99A5B", label: "Camel" },
      { hex: "#E6B325", label: "Honey Gold" },
      { hex: "#6FA84B", label: "Leaf Green" },
      { hex: "#2FA8A1", label: "Teal" },
      { hex: "#E4724A", label: "Coral" },
    ],
    reference: [
      { hex: "#EFE3C8", label: "Warm Cream" },
      { hex: "#C99A5B", label: "Camel" },
      { hex: "#BE8A4A", label: "Golden Tan" },
      { hex: "#E6B325", label: "Honey Gold" },
      { hex: "#9AAE4E", label: "Pear" },
      { hex: "#6FA84B", label: "Leaf Green" },
      { hex: "#2FA8A1", label: "Teal" },
      { hex: "#29B6A8", label: "Turquoise" },
      { hex: "#E4724A", label: "Coral" },
      { hex: "#D24A35", label: "Tomato Red" },
      { hex: "#7A5230", label: "Warm Brown" },
      { hex: "#A99B83", label: "Warm Grey" },
    ],
  },
  {
    key: "light-spring",
    family: "Spring",
    name: "Light Spring",
    note: "Light and warm — the gentlest end of the spring family.",
    swatches: [
      { hex: "#F5EEDC", label: "Paper" },
      { hex: "#F4E3A1", label: "Buttercream" },
      { hex: "#F4C7A8", label: "Soft Peach" },
      { hex: "#B7CE96", label: "Light Green" },
      { hex: "#9ED3D6", label: "Sky" },
      { hex: "#8FA6D6", label: "Periwinkle" },
    ],
    reference: [
      { hex: "#F5EEDC", label: "Paper" },
      { hex: "#F4E3A1", label: "Buttercream" },
      { hex: "#F4C7A8", label: "Soft Peach" },
      { hex: "#EF9E86", label: "Coral Pink" },
      { hex: "#CFC4B0", label: "Light Warm Grey" },
      { hex: "#CDA877", label: "Light Camel" },
      { hex: "#B7CE96", label: "Light Green" },
      { hex: "#9ED3D6", label: "Sky" },
      { hex: "#6FC2BC", label: "Light Teal" },
      { hex: "#8FA6D6", label: "Periwinkle" },
      { hex: "#B89A6A", label: "Warm Tan" },
      { hex: "#4A5E86", label: "Soft Navy" },
    ],
  },
  {
    key: "light-summer",
    family: "Summer",
    name: "Light Summer",
    note: "Light and cool, with rose and powder tones.",
    swatches: [
      { hex: "#EFE9E4", label: "Shell" },
      { hex: "#C5D4E2", label: "Powder Blue" },
      { hex: "#AAB5C6", label: "Dove Grey" },
      { hex: "#C2CDB4", label: "Soft Sage" },
      { hex: "#D5B6C0", label: "Petal" },
      { hex: "#8EA7B5", label: "Slate Blue" },
    ],
    reference: [
      { hex: "#EFE9E4", label: "Shell" },
      { hex: "#C5D4E2", label: "Powder Blue" },
      { hex: "#AAB5C6", label: "Dove Grey" },
      { hex: "#C2C4C9", label: "Cool Light Grey" },
      { hex: "#8EA7B5", label: "Slate Blue" },
      { hex: "#7E97B8", label: "Soft Denim" },
      { hex: "#C2CDB4", label: "Soft Sage" },
      { hex: "#D5B6C0", label: "Petal" },
      { hex: "#9FB0D6", label: "Periwinkle" },
      { hex: "#6F8BA8", label: "Cadet Blue" },
      { hex: "#5E6E7E", label: "Slate" },
      { hex: "#3F5470", label: "Soft Navy" },
    ],
  },
  {
    key: "true-summer",
    family: "Summer",
    name: "True Summer",
    note: "Cool and muted — grey undertones, rosy neutrals.",
    swatches: [
      { hex: "#E4DED3", label: "Bone" },
      { hex: "#6E8AA6", label: "Denim Blue" },
      { hex: "#4A6375", label: "Slate Blue" },
      { hex: "#6E9089", label: "Eucalyptus" },
      { hex: "#9E7A86", label: "Mulberry" },
      { hex: "#A64158", label: "Raspberry" },
    ],
    reference: [
      { hex: "#E4DED3", label: "Bone" },
      { hex: "#9AA1AB", label: "Cool Grey" },
      { hex: "#6E8AA6", label: "Denim Blue" },
      { hex: "#4A6375", label: "Slate Blue" },
      { hex: "#6E9089", label: "Eucalyptus" },
      { hex: "#3E5A55", label: "Soft Spruce" },
      { hex: "#9E7A86", label: "Mulberry" },
      { hex: "#7E5C6B", label: "Soft Plum" },
      { hex: "#A64158", label: "Raspberry" },
      { hex: "#8E6A66", label: "Rosy Brown" },
      { hex: "#2E435C", label: "Navy" },
      { hex: "#4F5B66", label: "Graphite" },
    ],
  },
  {
    key: "soft-summer",
    family: "Summer",
    name: "Soft Summer",
    note: "Muted, cool-neutral — everything grey-tinted and quiet.",
    swatches: [
      { hex: "#DFD8CC", label: "Oat" },
      { hex: "#8F8577", label: "Mushroom Taupe" },
      { hex: "#6F7E86", label: "Steel Grey" },
      { hex: "#8C9E83", label: "Lichen" },
      { hex: "#A68E8B", label: "Ash Rose" },
      { hex: "#4F5B66", label: "Graphite" },
    ],
    reference: [
      { hex: "#DFD8CC", label: "Oat" },
      { hex: "#8F8577", label: "Mushroom Taupe" },
      { hex: "#6F7E86", label: "Steel Grey" },
      { hex: "#7E909C", label: "Grey-Blue" },
      { hex: "#8C9E83", label: "Lichen" },
      { hex: "#5B6C60", label: "Muted Fern" },
      { hex: "#A68E8B", label: "Ash Rose" },
      { hex: "#876E73", label: "Dusty Mauve" },
      { hex: "#5E7E7A", label: "Soft Teal" },
      { hex: "#4F5B66", label: "Graphite" },
      { hex: "#3A4A5A", label: "Muted Navy" },
      { hex: "#50606C", label: "Slate" },
    ],
  },
  {
    key: "soft-autumn",
    family: "Autumn",
    name: "Soft Autumn",
    note: "Muted and warm — dusty olives, golden neutrals.",
    swatches: [
      { hex: "#D9CFB9", label: "Linen" },
      { hex: "#9A7F5A", label: "Wheat" },
      { hex: "#7E8460", label: "Olive Grove" },
      { hex: "#B58762", label: "Caramel" },
      { hex: "#8F6A5A", label: "Clay" },
      { hex: "#5B6C60", label: "Fern" },
    ],
    reference: [
      { hex: "#D9CFB9", label: "Linen" },
      { hex: "#9A7F5A", label: "Wheat" },
      { hex: "#7E8460", label: "Olive Grove" },
      { hex: "#5B6C60", label: "Fern" },
      { hex: "#B58762", label: "Caramel" },
      { hex: "#8F6A5A", label: "Clay" },
      { hex: "#897A64", label: "Warm Taupe" },
      { hex: "#6E5A45", label: "Soft Brown" },
      { hex: "#C2A172", label: "Camel" },
      { hex: "#4F6E68", label: "Muted Teal" },
      { hex: "#A4623F", label: "Soft Rust" },
      { hex: "#8C8170", label: "Warm Grey" },
    ],
  },
  {
    key: "true-autumn",
    family: "Autumn",
    name: "True Autumn",
    note: "Warm, rich, earth-saturated — the heart of the autumn family.",
    swatches: [
      { hex: "#D9C39A", label: "Light Camel" },
      { hex: "#B5842E", label: "Mustard Gold" },
      { hex: "#A4502A", label: "Rust" },
      { hex: "#4B5A2C", label: "Deep Olive" },
      { hex: "#6B3A2A", label: "Chestnut" },
      { hex: "#2F4E4A", label: "Forest Teal" },
    ],
    reference: [
      { hex: "#D9C39A", label: "Light Camel" },
      { hex: "#B5842E", label: "Mustard Gold" },
      { hex: "#A4502A", label: "Rust" },
      { hex: "#9E4A2E", label: "Brick" },
      { hex: "#4B5A2C", label: "Deep Olive" },
      { hex: "#2F4E4A", label: "Forest Teal" },
      { hex: "#6B3A2A", label: "Chestnut" },
      { hex: "#4A3220", label: "Chocolate" },
      { hex: "#7A5A2E", label: "Bronze" },
      { hex: "#2E5650", label: "Deep Teal" },
      { hex: "#C29A5E", label: "Camel" },
      { hex: "#5E4128", label: "Warm Brown" },
    ],
  },
  {
    key: "dark-autumn",
    family: "Autumn",
    name: "Dark Autumn",
    note: "Deep, warm, dramatic — the darkest end of the warm palettes.",
    swatches: [
      { hex: "#A88A55", label: "Old Gold" },
      { hex: "#3A2018", label: "Espresso" },
      { hex: "#6B2222", label: "Oxblood" },
      { hex: "#3B4A1F", label: "Dark Moss" },
      { hex: "#7A4A1F", label: "Tobacco" },
      { hex: "#1D2A2A", label: "Ink Pine" },
    ],
    reference: [
      { hex: "#A88A55", label: "Old Gold" },
      { hex: "#B08A50", label: "Camel" },
      { hex: "#3A2018", label: "Espresso" },
      { hex: "#2E1F15", label: "Dark Chocolate" },
      { hex: "#6B2222", label: "Oxblood" },
      { hex: "#7A3128", label: "Deep Brick" },
      { hex: "#3B4A1F", label: "Dark Moss" },
      { hex: "#7A4A1F", label: "Tobacco" },
      { hex: "#1D2A2A", label: "Ink Pine" },
      { hex: "#233A2E", label: "Deep Forest" },
      { hex: "#2A241E", label: "Warm Charcoal" },
      { hex: "#20303F", label: "Deep Navy" },
    ],
  },
  {
    key: "dark-winter",
    family: "Winter",
    name: "Dark Winter",
    note: "Deep, cool, high-contrast — black and jewel tones.",
    swatches: [
      { hex: "#ECEDEF", label: "True White" },
      { hex: "#14161C", label: "Jet Black" },
      { hex: "#1E2A44", label: "Dark Navy" },
      { hex: "#5E1A2B", label: "Bordeaux" },
      { hex: "#0E3B3A", label: "Spruce" },
      { hex: "#2B1F3F", label: "Aubergine" },
    ],
    reference: [
      { hex: "#ECEDEF", label: "True White" },
      { hex: "#CDD2D8", label: "Icy Grey" },
      { hex: "#14161C", label: "Jet Black" },
      { hex: "#2A2E36", label: "Charcoal" },
      { hex: "#1E2A44", label: "Dark Navy" },
      { hex: "#5E1A2B", label: "Bordeaux" },
      { hex: "#0E3B3A", label: "Spruce" },
      { hex: "#16403A", label: "Pine" },
      { hex: "#2B1F3F", label: "Aubergine" },
      { hex: "#143A40", label: "Deep Teal" },
      { hex: "#44505E", label: "Slate Grey" },
      { hex: "#6A7682", label: "Cool Steel" },
    ],
  },
  {
    key: "true-winter",
    family: "Winter",
    name: "True Winter",
    note: "Cool and clear — black, white, and primary jewels.",
    swatches: [
      { hex: "#F4F4F4", label: "Pure White" },
      { hex: "#0B0B10", label: "True Black" },
      { hex: "#14213F", label: "Navy" },
      { hex: "#1746C0", label: "Royal Blue" },
      { hex: "#C20E2E", label: "True Red" },
      { hex: "#0A6B4A", label: "Emerald" },
    ],
    reference: [
      { hex: "#F4F4F4", label: "Pure White" },
      { hex: "#CFD8E2", label: "Icy Blue-Grey" },
      { hex: "#0B0B10", label: "True Black" },
      { hex: "#25282E", label: "Charcoal" },
      { hex: "#14213F", label: "Navy" },
      { hex: "#1746C0", label: "Royal Blue" },
      { hex: "#C20E2E", label: "True Red" },
      { hex: "#0A6B4A", label: "Emerald" },
      { hex: "#0E5A3E", label: "Pine" },
      { hex: "#3E5C82", label: "Steel Blue" },
      { hex: "#4A2A66", label: "Imperial Purple" },
      { hex: "#C2C7CE", label: "Cool Grey" },
    ],
  },
  {
    key: "bright-winter",
    family: "Winter",
    name: "Bright Winter",
    note: "Cool, clear, saturated — the brightest of the cool palettes.",
    swatches: [
      { hex: "#F7F7F2", label: "Porcelain" },
      { hex: "#0E0E0E", label: "Obsidian" },
      { hex: "#1A53D0", label: "True Blue" },
      { hex: "#0AA06A", label: "Emerald" },
      { hex: "#DE1E3C", label: "Clear Red" },
      { hex: "#BDD0E6", label: "Icy Blue" },
    ],
    reference: [
      { hex: "#F7F7F2", label: "Porcelain" },
      { hex: "#CCD2DA", label: "Icy Grey" },
      { hex: "#BDD0E6", label: "Icy Blue" },
      { hex: "#0E0E0E", label: "Obsidian" },
      { hex: "#24272E", label: "Charcoal" },
      { hex: "#1A53D0", label: "True Blue" },
      { hex: "#1746A2", label: "Sapphire" },
      { hex: "#0AA06A", label: "Emerald" },
      { hex: "#00A2A8", label: "Bright Teal" },
      { hex: "#DE1E3C", label: "Clear Red" },
      { hex: "#15224A", label: "Navy" },
      { hex: "#C0186A", label: "Magenta" },
    ],
  },
];

const FAMILIES = ["Spring", "Summer", "Autumn", "Winter"];

const SUB_BY_FAMILY = {
  Spring: ["Light", "True", "Bright"],
  Summer: ["Light", "True", "Soft"],
  Autumn: ["Soft", "True", "Dark"],
  Winter: ["Dark", "True", "Bright"],
};

const TEE_STYLES = [
  { name: "The Weekend Tee",    cut: "boxy cotton",          price: "$68", swatchIdx: 0 },
  { name: "Garment-Dyed Crew",  cut: "heavyweight crew",     price: "$74", swatchIdx: 3 },
  { name: "Pima Long Sleeve",   cut: "long-sleeve pima",     price: "$88", swatchIdx: 5 },
  { name: "The Everyday",       cut: "regular-fit cotton",   price: "$62", swatchIdx: 1 },
  { name: "Linen Henley",       cut: "linen three-button",   price: "$96", swatchIdx: 2 },
  { name: "Boxy Pocket Tee",    cut: "pocket tee",           price: "$72", swatchIdx: 4 },
];

window.SEASONS = SEASONS;
window.FAMILIES = FAMILIES;
window.SUB_BY_FAMILY = SUB_BY_FAMILY;
window.TEE_STYLES = TEE_STYLES;
